spring:
  datasource:
    url: jdbc:mysql://192.168.1.52:3306/test_yjn?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Ewit@123
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 100
  redis:
    database: 0
    host: 192.168.1.52
    port: 6379
    password: 123456



