spring:
  datasource:
    url: jdbc:mysql://43.154.195.135:3306/db?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: yjn
    password: 123456
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 100
  redis:
    database: 0
    host: 192.168.1.52
    port: 6379
    password: 123456



#ddddd